apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-template-app2-deployment
  labels:
    app: fastapi-template-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-template-app2
  template:
    metadata:
      labels:
        app: fastapi-template-app2
    spec:
      containers:
      - name: fastapi-template-app2
        image: kpburgula/fastapi-template-app2
        ports:
        - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-template-app2-service
spec:
  type: NodePort
  selector:
    app: fastapi-template-app2
  ports:
  - port: 7777